/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.Member;
import BE.MembershipFee;
import BLL.MemberManager;
import BLL.MembershipTypeManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Chris
 */
public class SummerFee extends javax.swing.JFrame
{

    private static SummerFee instance = null;
    private MemberManager mManager;
    private MembershipTypeManager mtManager;
    private int age;
    private Calendar todayInvoice = new GregorianCalendar();
    private Calendar todayPayment = new GregorianCalendar();
    private int memberId = 1;

    /**
     * Creates new form AllMembers
     */
    private SummerFee()
    {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        checkBirth();


        mManager = MemberManager.getInstance();
        mtManager = MembershipTypeManager.getInstance();
        allMembers();

        spNames.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent lse)
            {
                insertMember();
                try
                {
                    Calendar sent = mtManager.getSent(memberId);
                    Calendar paid = mtManager.getPaid(memberId);

                    if (sent != null && (Calendar.getInstance().get(Calendar.YEAR) == sent.get(Calendar.YEAR)))
                    {
                        chkbInvoiceSent.setSelected(true);
                        chkbInvoiceSent.setEnabled(false);
                    }
                    else
                    {
                        chkbInvoiceSent.setSelected(false);
                        chkbInvoiceSent.setEnabled(true);
                    }

                    if (paid != null && (Calendar.getInstance().get(Calendar.YEAR) == paid.get(Calendar.YEAR)))
                    {
                        chkbPaid.setSelected(true);
                        chkbPaid.setEnabled(false);
                    }
                    else if(sent== null)
                    {
                        chkbPaid.setEnabled(false);
                        chkbPaid.setSelected(false);
                    }
                    else
                    {
                        chkbPaid.setEnabled(true);
                        chkbPaid.setSelected(false);
                    }


                }
                catch (Exception e)
                {
                    System.err.println("Error - " + e.getMessage());
                }
            }
        });
    }

    public static SummerFee getInstance()
    {
        if (instance == null)
        {
            instance = new SummerFee();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnBack = new javax.swing.JButton();
        spMember = new javax.swing.JScrollPane();
        spNames = new javax.swing.JList();
        lblBodyText = new javax.swing.JLabel();
        pnlMemberInfo = new javax.swing.JPanel();
        lblNametext = new javax.swing.JLabel();
        lblMemberIDtext = new javax.swing.JLabel();
        lblAddresstext = new javax.swing.JLabel();
        lblZipCitytext = new javax.swing.JLabel();
        lblEmailtext = new javax.swing.JLabel();
        lblPhoneNumbertext = new javax.swing.JLabel();
        lblMemberID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblZipCity = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        chkbPaid = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        chkbInvoiceSent = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Tilbage");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });

        spNames.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems ID : Navn"));
        spMember.setViewportView(spNames);

        lblBodyText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodyText.setText("Tryk på et medlem for mere info");

        pnlMemberInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems info"));

        lblNametext.setText("Navn:");

        lblMemberIDtext.setText("Medlems ID:");

        lblAddresstext.setText("Adresse:");

        lblZipCitytext.setText("Postnr/by:");

        lblEmailtext.setText("Email:");

        lblPhoneNumbertext.setText("Telefonnr:");

        javax.swing.GroupLayout pnlMemberInfoLayout = new javax.swing.GroupLayout(pnlMemberInfo);
        pnlMemberInfo.setLayout(pnlMemberInfoLayout);
        pnlMemberInfoLayout.setHorizontalGroup(
            pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblNametext)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblAddresstext)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblEmailtext))
                .addGap(18, 18, 18)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblZipCity)
                    .addComponent(lblAddress)
                    .addComponent(lblMemberID)
                    .addComponent(lblName)
                    .addComponent(lblPhoneNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMemberInfoLayout.setVerticalGroup(
            pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblMemberID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNametext)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddresstext)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblZipCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailtext)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblPhoneNumber))
                .addGap(72, 72, 72))
        );

        chkbPaid.setText("Betalt månedskontingent");
        chkbPaid.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkbPaidActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sommer kontingent");

        btnUpdate.setText("Opdater");
        btnUpdate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUpdateActionPerformed(evt);
            }
        });

        chkbInvoiceSent.setText("Sendt Giro");
        chkbInvoiceSent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkbInvoiceSentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlMemberInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkbInvoiceSent)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkbPaid)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBack))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBodyText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(310, 310, 310))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBodyText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMemberInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnUpdate)
                            .addComponent(chkbPaid)
                            .addComponent(chkbInvoiceSent)))
                    .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        dispose();
        spNames.clearSelection();
        Administration.getInstance().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void chkbInvoiceSentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkbInvoiceSentActionPerformed
    {//GEN-HEADEREND:event_chkbInvoiceSentActionPerformed
        invoiceSent();
    }//GEN-LAST:event_chkbInvoiceSentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUpdateActionPerformed
    {//GEN-HEADEREND:event_btnUpdateActionPerformed
        updatePayment();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void chkbPaidActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkbPaidActionPerformed
    {//GEN-HEADEREND:event_chkbPaidActionPerformed
        feePaid();
    }//GEN-LAST:event_chkbPaidActionPerformed

    private void allMembers()
    {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        try
        {
            ArrayList names = mManager.getByName();
            for (int i = 0; i < names.size(); i++)
            {
                String name = names.get(i).toString();
                i++;
                name = name + " : " + names.get(i).toString();
                model.addElement(name);
            }
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }
        spNames.setModel(model);
    }

    public void insertMember()
    {   
        int id = 1;
        String name = (String) spNames.getSelectedValue();
        if(name != null)
        {
        String parts[] = name.split(" : ");
        id = Integer.parseInt(parts[0]);
        }
        try
        {
            Member m = mManager.getMemberByID(id);
            lblMemberID.setText(Integer.toString(id));
            memberId = id;
            lblName.setText(m.getFirstName() + " " + m.getLastName());
            lblAddress.setText(m.getAddress());
            lblZipCity.setText(m.getZipCode() + "  /  " + m.getCity());
            lblEmail.setText(m.getEmail());
            lblPhoneNumber.setText(Integer.toString(m.getPhoneNumber()));
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }

    }

    private void invoiceSent()
    {
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int month = Calendar.getInstance().get(Calendar.MONTH);
        int day = Calendar.getInstance().get(Calendar.DATE);

        todayInvoice.set(year, month, day, 0, 0);
    }

    private void feePaid()
    {
        int year = Calendar.getInstance().get(Calendar.YEAR);
        int month = Calendar.getInstance().get(Calendar.MONTH);
        int day = Calendar.getInstance().get(Calendar.DATE);

        todayPayment.set(year, month, day, 0, 0);
    }

    private void updatePayment()
    {
        int typeId;
        try
        {
            Calendar sent = mtManager.getSent(memberId);
            Calendar paid = mtManager.getPaid(memberId);

            if (sent == null && chkbInvoiceSent.isSelected() && chkbInvoiceSent.isEnabled())
            {

                if (age < 18)
                {
                    typeId = 1;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.invoiceSent(mf);
                    Administration.getInstance().setVisible(true);
                }

                if (age >= 60)
                {
                    typeId = 3;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.invoiceSent(mf);
                    Administration.getInstance().setVisible(true);
                }

                if (age >= 18 && age < 60)
                {
                    typeId = 2;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.invoiceSent(mf);
                    Administration.getInstance().setVisible(true);
                }
            }
            if (sent != null && chkbPaid.isSelected() && chkbPaid.isEnabled())
            {
                if (age < 18)
                {
                    typeId = 1;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.paymentReceived(memberId, todayPayment);
                    Administration.getInstance().setVisible(true);
                }

                if (age >= 60)
                {
                    typeId = 3;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.paymentReceived(memberId, todayPayment);
                    Administration.getInstance().setVisible(true);
                }

                if (age >= 18 && age < 60)
                {
                    typeId = 2;
                    MembershipFee mf = new MembershipFee(memberId, typeId, todayInvoice);

                    mtManager.paymentReceived(memberId, todayPayment);
                    Administration.getInstance().setVisible(true);
                }
            }
            else if (sent != null && (!chkbPaid.isSelected() && chkbPaid.isEnabled()))
            {
                JOptionPane.showMessageDialog(null, "MedlemsNr eksisterer allerede i systemet!", "Advarsel", JOptionPane.INFORMATION_MESSAGE);
            }

        }
        catch (Exception e)
        {
            System.err.println("ERROR - " + e.getMessage());
        }
    }

    private void checkBirth()
    {

        try
        {
            Calendar mbday = MemberManager.getInstance().getMembersBDayByID(memberId);
            Calendar now = new GregorianCalendar();
            int nowMonth = now.get(Calendar.MONTH) + 1;
            int nowYear = now.get(Calendar.YEAR) + 1900;
            int month = mbday.get(Calendar.MONTH) + 1;
            age = nowYear - (mbday.get(Calendar.YEAR) + 1900);

            if (month > nowMonth)
            {
                age--;
            }
            else if (month == nowMonth)
            {
                int nowDay = now.get(Calendar.DATE);

                if (mbday.get(Calendar.DATE) > nowDay)
                {
                    age--;
                }
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(CourtBooking.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SummerFee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkbInvoiceSent;
    private javax.swing.JCheckBox chkbPaid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddresstext;
    private javax.swing.JLabel lblBodyText;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailtext;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblMemberIDtext;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNametext;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumbertext;
    private javax.swing.JLabel lblZipCity;
    private javax.swing.JLabel lblZipCitytext;
    private javax.swing.JPanel pnlMemberInfo;
    private javax.swing.JScrollPane spMember;
    private javax.swing.JList spNames;
    // End of variables declaration//GEN-END:variables
}
