/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BE.Member;
import BLL.MemberManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Chris
 */
public class SummerFee extends javax.swing.JFrame
{

    private static SummerFee instance = null;
    private MemberManager mManager;

    /**
     * Creates new form AllMembers
     */
    private SummerFee()
    {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        mManager = MemberManager.getInstance();
        allMembers();

        spNames.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent lse)
            {
                insertMember();
            }
        });
    }

    public static SummerFee getInstance()
    {
        if (instance == null)
        {
            instance = new SummerFee();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnBack = new javax.swing.JButton();
        spMember = new javax.swing.JScrollPane();
        spNames = new javax.swing.JList();
        lblBodyText = new javax.swing.JLabel();
        pnlMemberInfo = new javax.swing.JPanel();
        lblNametext = new javax.swing.JLabel();
        lblMemberIDtext = new javax.swing.JLabel();
        lblAddresstext = new javax.swing.JLabel();
        lblZipCitytext = new javax.swing.JLabel();
        lblEmailtext = new javax.swing.JLabel();
        lblPhoneNumbertext = new javax.swing.JLabel();
        lblMemberID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblZipCity = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        chkbMonthlyPay = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Tilbage");
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });

        spNames.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems ID : Navn"));
        spMember.setViewportView(spNames);

        lblBodyText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBodyText.setText("Tryk på et medlem for mere info");

        pnlMemberInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems info"));

        lblNametext.setText("Navn:");

        lblMemberIDtext.setText("Medlems ID:");

        lblAddresstext.setText("Adresse:");

        lblZipCitytext.setText("Postnr/by:");

        lblEmailtext.setText("Email:");

        lblPhoneNumbertext.setText("Telefonnr:");

        javax.swing.GroupLayout pnlMemberInfoLayout = new javax.swing.GroupLayout(pnlMemberInfo);
        pnlMemberInfo.setLayout(pnlMemberInfoLayout);
        pnlMemberInfoLayout.setHorizontalGroup(
            pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblNametext)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblAddresstext)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblEmailtext))
                .addGap(18, 18, 18)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblZipCity)
                    .addComponent(lblAddress)
                    .addComponent(lblMemberID)
                    .addComponent(lblName)
                    .addComponent(lblPhoneNumber))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMemberInfoLayout.setVerticalGroup(
            pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblMemberID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNametext)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddresstext)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblZipCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailtext)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblPhoneNumber))
                .addGap(72, 72, 72))
        );

        chkbMonthlyPay.setText("Betalt månedskontingent");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sommer kontingent");

        btnUpdate.setText("Opdater");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlMemberInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chkbMonthlyPay)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBack))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBodyText, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(310, 310, 310))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBodyText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMemberInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBack)
                                .addComponent(btnUpdate))
                            .addComponent(chkbMonthlyPay)))
                    .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        dispose();
        Administration.getInstance().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    public void allMembers()
    {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        try
        {
            ArrayList names = mManager.getByName();
            for (int i = 0; i < names.size(); i++)
            {
                String name = names.get(i).toString();
                i++;
                name = name + " : " + names.get(i).toString();
                model.addElement(name);
            }
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }
        spNames.setModel(model);
    }

    public void insertMember()
    {
        String name = (String) spNames.getSelectedValue();
        String parts[] = name.split(" : ");
        int id = Integer.parseInt(parts[0]);
        try
        {
            Member m = mManager.getMemberByID(id);
            lblMemberID.setText(Integer.toString(m.getId()));
            lblName.setText(m.getFirstName() + " " + m.getLastName());
            lblAddress.setText(m.getAddress());
            lblZipCity.setText(m.getZipCode() + "  /  " + m.getCity());
            lblEmail.setText(m.getEmail());
            lblPhoneNumber.setText(Integer.toString(m.getPhoneNumber()));
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SummerFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SummerFee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkbMonthlyPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddresstext;
    private javax.swing.JLabel lblBodyText;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailtext;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblMemberIDtext;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNametext;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumbertext;
    private javax.swing.JLabel lblZipCity;
    private javax.swing.JLabel lblZipCitytext;
    private javax.swing.JPanel pnlMemberInfo;
    private javax.swing.JScrollPane spMember;
    private javax.swing.JList spNames;
    // End of variables declaration//GEN-END:variables
}
