package GUI;

import BE.Member;
import BLL.MemberManager;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class WinterFee extends javax.swing.JFrame
{
    private static WinterFee instance = null;
    private MemberManager mManager;

    /**
     * Constructor for the winter fee class
     */
    private WinterFee()
    {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        mManager = MemberManager.getInstance();
        allMembers();

        spNames.addListSelectionListener(new ListSelectionListener()
        {
            @Override
            public void valueChanged(ListSelectionEvent lse)
            {
                insertMember();
            }
        });
    }

    /**
     * Conversion of the winter fee class to a singleton
     * @return An instance of the winter fee class
     */
    public static WinterFee getInstance()
    {
        if (instance == null)
        {
            instance = new WinterFee();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnCancel = new javax.swing.JButton();
        spMember = new javax.swing.JScrollPane();
        spNames = new javax.swing.JList();
        lblMember = new javax.swing.JLabel();
        pnMemberInfo = new javax.swing.JPanel();
        lblNametext = new javax.swing.JLabel();
        lblMemberIDtext = new javax.swing.JLabel();
        lblAddresstext = new javax.swing.JLabel();
        lblZipCitytext = new javax.swing.JLabel();
        lblEmailtext = new javax.swing.JLabel();
        lblPhoneNumbertext = new javax.swing.JLabel();
        lblMemberID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblZipCity = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCancel.setText("Tilbage");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        spNames.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems ID : Navn"));
        spMember.setViewportView(spNames);

        lblMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMember.setText("Tryk på et medlem for mere info");

        pnMemberInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Medlems info"));

        lblNametext.setText("Navn:");

        lblMemberIDtext.setText("Medlems ID:");

        lblAddresstext.setText("Adresse:");

        lblZipCitytext.setText("Postnr/by:");

        lblEmailtext.setText("Email:");

        lblPhoneNumbertext.setText("Telefonnr:");

        javax.swing.GroupLayout pnMemberInfoLayout = new javax.swing.GroupLayout(pnMemberInfo);
        pnMemberInfo.setLayout(pnMemberInfoLayout);
        pnMemberInfoLayout.setHorizontalGroup(
            pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMemberInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblNametext)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblAddresstext)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblEmailtext))
                .addGap(18, 18, 18)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblZipCity)
                    .addComponent(lblAddress)
                    .addComponent(lblMemberID)
                    .addComponent(lblName)
                    .addComponent(lblPhoneNumber))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        pnMemberInfoLayout.setVerticalGroup(
            pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMemberInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberIDtext)
                    .addComponent(lblMemberID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNametext)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddresstext)
                    .addComponent(lblAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZipCitytext)
                    .addComponent(lblZipCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailtext)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnMemberInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumbertext)
                    .addComponent(lblPhoneNumber))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnMemberInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnCancel)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMember, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnMemberInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addComponent(spMember, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        dispose();
        Administration.getInstance().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Updates the list model in winter fee to show all members currently 
     * in the club
     */
    public void allMembers()
    {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        try
        {
            ArrayList names = mManager.getByName();
            for (int i = 0; i < names.size(); i++)
            {
                String name = names.get(i).toString();
                i++;
                name = name + " : " + names.get(i).toString();
                model.addElement(name);
            }
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }
        spNames.setModel(model);
    }

    /**
     * Provides the member information requested by the text fields on the gui
     */
    public void insertMember()
    {
        String name = (String) spNames.getSelectedValue();
        String parts[] = name.split(" : ");
        int id = Integer.parseInt(parts[0]);
        try
        {
            Member m = mManager.getMemberByID(id);
            lblMemberID.setText(Integer.toString(m.getId()));
            lblName.setText(m.getFirstName() + " " + m.getLastName());
            lblAddress.setText(m.getAddress());
            lblZipCity.setText(m.getZipCode() + "  /  " + m.getCity());
            lblEmail.setText(m.getEmail());
            lblPhoneNumber.setText(Integer.toString(m.getPhoneNumber()));
        }
        catch (SQLException e)
        {
            System.out.println("ERROR - " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Get system look and feel
         */
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e)
        {
            //Do nothing
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new WinterFee().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddresstext;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailtext;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblMemberIDtext;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNametext;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumbertext;
    private javax.swing.JLabel lblZipCity;
    private javax.swing.JLabel lblZipCitytext;
    private javax.swing.JPanel pnMemberInfo;
    private javax.swing.JScrollPane spMember;
    private javax.swing.JList spNames;
    // End of variables declaration//GEN-END:variables
}
